import './globals.css'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import { Navigation } from '@/components'
import newrelic from 'newrelic';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Family Guy',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  if (newrelic.agent.collector.isConnected() === false) {
    await new Promise((resolve) => {
      newrelic.agent.on("connected", resolve)
    })
  }

  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
    allowTransactionlessInjection: true,
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}

        <Script
          id="nr-browser-agent"
          dangerouslySetInnerHTML={{__html: browserTimingHeader}}
        />
      </body>
    </html>
  )
}
